### ISSUE TITLE
Add Preprocessing to the input string to make it more user friendly

### ISSUE THREAD

**Issue by PrateekNITH** [PrateekNITH/Num-Meth#5]

**Comment by PrateekNITH** [comment]
In the file, main.py, the user knowing about python and its math library will be able to use this code for mathematical operations.
I want that it should be made more user friendly.

for example, anyone will be giving this type of input: -
x*(math.log(x**3,10))+math.cos(x+30)

I want this expression to look like this: -
x*log(x^3,10)+cos(x+30)

**Comment by SuphalBhattarai** [comment]
just import everything from math like
`from math import *`
then you can do something like this
`from math import *

x = 2
m = x * log(x ^ 3, 10) + cos(x + 30)
print(m)
`
